Create few menu pages with curated posts and updated dropdowns.
IntEL4CoRo/ViB-public pull request #1
Opened 2024-02-21 10:52 UTC by Srikanth635

Duplicate content templates are present in my repo, will be removed in further updates.

2024-02-21 15:19 UTC, yxzhan requested changes
Please update `.github/workflows/hugo.yml` and `config.toml` before the updates can be merged.

2024-02-21 15:19 UTC, yxzhan commented on config.toml
> +baseurl = "https://srikanth635.github.io/ViB-public/"
It is not necessary to have the whole domain name in the baseurl.
Please updated it as below to make the config works on both repos.
```
baseurl = "ViB-public/"
```

2024-02-21 15:19 UTC, yxzhan commented on layouts/shortcodes/action_forms.html
It seems like the select boxs are hardcoded in a  a fixed hierarchy,  Environment =>  Robot => Task.
It is OK to do so for now. But if there are new types of options, this widget will likely need to be rewritten.

2024-02-23 12:29 UTC, Srikanth635 commented on layouts/shortcodes/action_forms.html
Yeah, for now this works. I'll rework on it.

2024-02-23 14:24 UTC, closed without merging